### ISSUE TITLE
Dataset no found

### ISSUE THREAD

**Issue by lcchenjh** [navreeetkaur/Video-Skimming#1]
Thank you for your nice work. But the link of dataset is no found, could you please update this?

**Comment by navreeetkaur** [comment]
Hi,

The link of the dataset was provided by my professor at the time of doing
this assignment. He might have taken it down, which is why the link is no
longer available.

You can make the dataset yourself too, by extracting frames which have
written content on them in videos like these
<https://www.youtube.com/watch?v=Eknlx7zHBVo>. Similar videos are available
on this <https://www.youtube.com/channel/UC640y4UvDAlya_WOj5U4pfA> channel
on YouTube.

Hope this helps.

Regards,
Navreet
